runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
# - url: /templates
#   static_dir: templates
#   application_readable: true
- url: /.*
  script: main.app

libraries:
# - name: webapp2
#   version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest
# [END handlers]
